dev:
  container_name: learn
  build: .
  volumes:
    - ./:/opt/learn
  env_file: ./env/dev.env
  command: ['/bin/bash']
test:
  container_name: learn
  build: .
  env_file: ./env/dev.env
  command: ['bats ./tests/integration']
