#Select the classification as the Y-variables
CLASSIFICATION = factor(CLASS5)
#Insert selected variable names into MANOVA
#MV <- lm(formula = cbind(B1_MEAN,B2_MEAN,B3_MEAN,B4_MEAN,B4_STDEV,B5_MEAN,
#			B5_STDEV,LVI_LAISRS,LVI_PCA1S,LVI_PCA2S,LVI_NDVI43M,
#			LVI_NDVI45S,LVI_NDVI73M,
#			LVI_NDVI73S) ~ CLASSIFICATION, data = lvinew)
MV <- lm(cbind(B1_MEAN,B1_STDEV,B2_MEAN,B2_STDEV, 
		B3_MEAN,B3_STDEV,B4_MEAN,B4_STDEV,B5_MEAN,B5_STDEV,
		B7_MEAN,B7_STDEV,LVI_LAIIRM,LVI_LAIIRS,LVI_LAISRM,LVI_LAISRS, 
		LVI_PCA1M,LVI_PCA1S,LVI_PCA2M,LVI_PCA2S,LVI_NDVI35M,LVI_NDVI35S,
		LVI_NDVI43M,LVI_NDVI43S,LVI_NDVI45M,LVI_NDVI45S,LVI_NDVI73M, 
		LVI_NDVI73S,LVI_BRIGHTM,LVI_BRIGHTS,LVI_GREENM,LVI_GREENS,
		LVI_WETM,LVI_WETS)~CLASSIFICATION, data = lvinew)

#Print mean values
mvCoef <-MV
mvCoef


#Print ANOVA indicating significance of differences between the means for each variable
mvSummary<-summary(MV)
mvSummary
library(MASS)
MV2<-manova(cbind(B1_MEAN,B2_MEAN,B3_MEAN,B4_MEAN,B4_STDEV,B5_MEAN,
			B5_STDEV,LVI_LAISRS,LVI_PCA1S,LVI_PCA2S,LVI_NDVI43M,
			LVI_NDVI45S,LVI_NDVI73M,
			LVI_NDVI73S) ~ CLASSIFICATION, data = lvinew)
