a <- sfa(LNN ~ LNDG, data = cdiData, ineffDecrease = TRUE, truncNorm = FALSE, timeEffect = FALSE, startVal = NULL)
b <- sfa(LNN ~ LNDG + LNLMAX, data = cdiData, ineffDecrease = TRUE, truncNorm = FALSE, timeEffect = FALSE, startVal = NULL)
c <- sfa(LNN ~ LNDG + LNLMAX + LNDGLM, data = cdiData, ineffDecrease = TRUE, truncNorm = FALSE, timeEffect = FALSE, startVal = NULL)
d <- sfa(LNN ~ LNDG + LNLAREA, data = cdiData, ineffDecrease = TRUE, truncNorm = FALSE, timeEffect = FALSE, startVal = NULL)
e <- sfa(LNN ~ LNDG + LNLAREA + LNDGLA, data = cdiData, ineffDecrease = TRUE, truncNorm = FALSE, timeEffect = FALSE, startVal = NULL)
f <- sfa(LNN ~ LNDG + LNGINI, data = cdiData, ineffDecrease = TRUE, truncNorm = FALSE, timeEffect = FALSE, startVal = NULL)
g <- sfa(LNN ~ LNDG + LNGINI + LNDGGI, data = cdiData, ineffDecrease = TRUE, truncNorm = FALSE, timeEffect = FALSE, startVal = NULL)
h <- sfa(LNN ~ LNDG + LNCDI, data = cdiData, ineffDecrease = TRUE, truncNorm = FALSE, timeEffect = FALSE, startVal = NULL)
i <- sfa(LNN ~ LNDG + LNCDI + LNDGCD, data = cdiData, ineffDecrease = TRUE, truncNorm = FALSE, timeEffect = FALSE, startVal = NULL)
j <- sfa(LNN ~ LNCDI, data = cdiData, ineffDecrease = TRUE, truncNorm = FALSE, timeEffect = FALSE, startVal = NULL)
k <- sfa(LNN ~ LNLAREA, data = cdiData, ineffDecrease = TRUE, truncNorm = FALSE, timeEffect = FALSE, startVal = NULL)
l <- sfa(LNN ~ LNLMAX, data = cdiData, ineffDecrease = TRUE, truncNorm = FALSE, timeEffect = FALSE, startVal = NULL)
m <- sfa(LNN ~ LNGINI, data = cdiData, ineffDecrease = TRUE, truncNorm = FALSE, timeEffect = FALSE, startVal = NULL)
n <- sfa(LNN ~ LNDG +LNDGLM, data = cdiData, ineffDecrease = TRUE, truncNorm = FALSE, timeEffect = FALSE, startVal = NULL)
o <- sfa(LNN ~ LNDG +LNDGLA, data = cdiData, ineffDecrease = TRUE, truncNorm = FALSE, timeEffect = FALSE, startVal = NULL)
p <- sfa(LNN ~ LNDG +LNDGCD, data = cdiData, ineffDecrease = TRUE, truncNorm = FALSE, timeEffect = FALSE, startVal = NULL)
q <- sfa(LNN ~ LNDG +LNDGGI, data = cdiData, ineffDecrease = TRUE, truncNorm = FALSE, timeEffect = FALSE, startVal = NULL)
r <- sfa(LNN ~ LNLMAX +LNDGLM, data = cdiData, ineffDecrease = TRUE, truncNorm = FALSE, timeEffect = FALSE, startVal = NULL)
s <- sfa(LNN ~ LNLAREA +LNDGLA, data = cdiData, ineffDecrease = TRUE, truncNorm = FALSE, timeEffect = FALSE, startVal = NULL)
t <- sfa(LNN ~ LNCDI +LNDGCD, data = cdiData, ineffDecrease = TRUE, truncNorm = FALSE, timeEffect = FALSE, startVal = NULL)
u <- sfa(LNN ~ LNGINI +LNDGGI, data = cdiData, ineffDecrease = TRUE, truncNorm = FALSE, timeEffect = FALSE, startVal = NULL)
v <- sfa(LNLMAX ~ LNDG +LNN, data = cdiData, ineffDecrease = TRUE, truncNorm = FALSE, timeEffect = FALSE, startVal = NULL)
w <- sfa(LNLAREA ~ LNDG +LNN, data = cdiData, ineffDecrease = TRUE, truncNorm = FALSE, timeEffect = FALSE, startVal = NULL)
x <- sfa(LNCDI ~ LNDG +LNN, data = cdiData, ineffDecrease = TRUE, truncNorm = FALSE, timeEffect = FALSE, startVal = NULL)
#y <- sfa(LNGINI ~ LNDG +LNN, data = cdiData, ineffDecrease = TRUE, truncNorm = FALSE, timeEffect = FALSE, startVal = NULL)
z <- sfa(LNLMAX ~ LNDG, data = cdiData, ineffDecrease = TRUE, truncNorm = FALSE, timeEffect = FALSE, startVal = NULL)
aa <- sfa(LNLAREA ~ LNDG, data = cdiData, ineffDecrease = TRUE, truncNorm = FALSE, timeEffect = FALSE, startVal = NULL)
ab <- sfa(LNCDI ~ LNDG, data = cdiData, ineffDecrease = TRUE, truncNorm = FALSE, timeEffect = FALSE, startVal = NULL)
ac <- sfa(LNLMAX ~ LNN, data = cdiData, ineffDecrease = TRUE, truncNorm = FALSE, timeEffect = FALSE, startVal = NULL)
ad <- sfa(LNLAREA ~ LNN, data = cdiData, ineffDecrease = TRUE, truncNorm = FALSE, timeEffect = FALSE, startVal = NULL)
ae <- sfa(LNCDI ~ LNN, data = cdiData, ineffDecrease = TRUE, truncNorm = FALSE, timeEffect = FALSE, startVal = NULL)


aTest <- lrtest(a)
bTest <- lrtest(b)
cTest <- lrtest(c)
dTest <- lrtest(d)
eTest <- lrtest(e)
fTest <- lrtest(f)
gTest <- lrtest(g)
hTest <- lrtest(h)
iTest <- lrtest(i)
jTest <- lrtest(j)
kTest <- lrtest(k)
lTest <- lrtest(l)
mTest <- lrtest(m)
nTest <- lrtest(n)
oTest <- lrtest(o)
pTest <- lrtest(p)
qTest <- lrtest(q)
rTest <- lrtest(r)
sTest <- lrtest(s)
tTest <- lrtest(t)
uTest <- lrtest(u)
vTest <- lrtest(v)
wTest <- lrtest(w)
xTest <- lrtest(x)
#yTest <- lrtest(y)
zTest <- lrtest(z)
aaTest <- lrtest(aa)
abTest <- lrtest(ab)
acTest <- lrtest(ac)
adTest <- lrtest(ad)
aeTest <- lrtest(ae)


